# Alpine Linux with OpenJDK JRE
FROM adoptopenjdk:11-jre-hotspot

ADD teamsnakes-region-server.jar teamsnakes-region-server.jar

# TODO: use environment variable $env to set spring profile
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "-Dspring.profiles.active=test", "/teamsnakes-region-server.jar"]
